[package]
name = "yeet-yoink"
version = "0.0.0-unstable"
description ="A file storage API"
license = "EUPL-1.2"
keywords = ["file-storage", "cloud-storage"]
repository = "https://github.com/sunsided/yeet-yoink"
readme = "README.md"
authors = ["Markus Mayer <widemeadows@gmail.com>"]
edition = "2021"
rust-version = "1.68.0"

[dependencies]
clap = { version = "4.2.4", features = ["env"] }
dotenvy = "0.15.7"
futures = "0.3.28"
tokio = { version = "1.28.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "parking_lot", "tracing-log", "json"] }
warp = "0.3.4"
