version: "3.8"
services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  memcached:
    image: "memcached:alpine"
    entrypoint:
      - memcached
      - -m 64
      - --verbose
      - --enable-largepages
    expose:
      - "11211/tcp"
    ports:
      - "11211:11211"
    healthcheck:
      test: echo stats | nc 127.0.0.1 11211
      interval: 10s
      retries: 60
